### ISSUE TITLE
Add YouTube social icon/link to ALTERNATIVE channel

### ISSUE THREAD

**Issue by ptashev** [ALTERNATIVE-EU/ckanext-alternative_theme#3]
https://www.youtube.com/@alternative-project

![Image](https://github.com/ALTERNATIVE-EU/ckanext-alternative_theme/assets/57897968/a6bfe149-5cd4-47ce-aef1-66709fc72b75)

**Comment by vikig07** [comment]
https://github.com/ALTERNATIVE-EU/ckanext-alternative_theme/commit/ddb6843d2efd7dd82cfcad9338cdd52e685346ab

**Comment by ptashev** [comment]
Tested! Done!
