### ISSUE TITLE
Update Footer Links as Specified

### ISSUE THREAD

**Issue by ptashev** [ALTERNATIVE-EU/ckanext-alternative_theme#6]
Link 1: 
Current name: ALTERNATIVE CDP
New name: ALTERNATIVE GitHub
New link: https://github.com/ALTERNATIVE-EU (should be open in a new browser tab)

Link 2:
Current name: ALTERNATIVE API
New name: Platform Documentation
New link: https://alternative-eu.github.io/alternative.github.io (should be open in a new browser tab)

**Comment by ignatov17** [comment]
Done.
